import Head from 'next/head';
import Home from './home/index';

export default function Main() {
  return (
    <>
      <Head>
        <title>HAZZYSㅣ온라인 공식 플래그십 스토어</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home/>
    </>
  )
}
